version: "3.8"

services:
    mariadb:
        image: mariadb:10.7.8-focal
        container_name: mariadb
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

    redis:
        image: redis:6.2.11-alpine3.17
        container_name: redis
        restart: always
        command: redis-server --appendonly yes --requirepass  "${REDIS_PASSWORD}"
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        ports:
            - 8081:80
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - mariadb

    php:
        build:
            context: .
            target: php
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=${APP_ENV}
            - APP_KEY=${APP_KEY}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - redis
            - mariadb

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        restart: always

volumes:
    db-data:
    redis_data:


networks:
    invoicesnetwork:


